<?php
$config=[
	/*
	logを保存するディレクトリとBasic認証の設定
	*/
	'log'=>[
		'dir'=>$_ENV['LOG_DIR'],
		'username'=>$_ENV['LOG_USER'],
		'password'=>$_ENV['LOG_PASSWORD'],
	],
	/*
	メール送信に使うSMTPの設定、設定しない場合はPHPのmail関数で送信されます
	*/
	'smtp'=>[
		'host'=>$_ENV['SMTP_HOST'],
		'username'=>$_ENV['SMTP_USER'],
		'password'=>$_ENV['SMTP_PASSWORD'],
	],
	/*
	mailディレクトリに設定された各メールのテンプレートファイルにおいて
	$to,$from,$subject変数が設定されなかった場合の初期値
	*/
	'defaultHeaders'=>[
		'from'=>'Example<noreply@catpow.info>',
		'to'=>'Example<norepl@catpow.info>',
		'subject'=>'Mail Send from MailForm'
	],
	/*
	カルマ値の設定
	カルマ値は攻撃の可能性のある入力およびメール送信ごとに増加し
	連続投稿や攻撃的入力を行ったユーザーのIPアドレスからの利用を一定期間凍結します
	*/
	'karma'=>[
		'recovery'=>100,//1日あたりのカルマ減少値
		'thredshold'=>1000,//ユーザーのIPアドレスからフォームを利用できなくするカルマ値の閾値
		'values'=>[
			'send_mail'=>10,//大量連続投稿防止のための通常のメール送信にともなうカルマ増加値、フォームの送信一回ではなくメール１通ごとに増加します
			'put_log'=>10,//大量連続投稿防止のための通常のログ記録にともなうカルマ増加値/
			'doubt_input'=>10,//クオートやバックスラッシュ
			'danger_input'=>500,//スクリプトタグや制御文字、選択肢にない値など手動では入力し得ない入力値を含んでいる場合のカルマ増加値
			'file_upload'=>50,//大量連続アップロード防止のための通常のファイルアップロードにともなうカルマ増加値
			'heavy_file_upload'=>200,//設定したファァイルアップロード最大サイズ２倍より大きいファイルをアップロードした際のカルマ増加値の
			'danger_file_upload'=>500//ファイルタイプがapplicationdで許可していないファイルタイプのファイルをアップロードした際のカルマ増加値
		]
	],
	/*
	フォームで使う入力項目の設定
	ここで設定したものだけを受け付けます
	*/
	'inputs'=>[
		'type'=>['type'=>'radio','label'=>'お問合せ内容','value'=>['送信テスト'=>'test','その他'=>'etc'],'required'=>true],
		'name'=>['type'=>'text','label'=>'お名前','size'=>30,'required'=>true],
		'kana'=>['type'=>'katakana','label'=>'フリガナ','reflect'=>'name','size'=>30,'required'=>true],
		'email'=>['type'=>'email','label'=>'メールアドレス','size'=>40,'required'=>true],
		'email_confirm'=>['type'=>'confirm','label'=>'再入力','caption'=>'もう一度入力してください','size'=>40,'reflect'=>'email','required'=>true],
		'zipcode'=>['type'=>'ZipCode','label'=>'郵便番号','pref'=>'prefecture','addr'=>'address'],
		'prefecture'=>['type'=>'select_json','value'=>'prefecture','label'=>'都道府県'],
		'address'=>['type'=>'text','label'=>'住所','size'=>50],
		'body'=>['type'=>'textarea','label'=>'お問合せ内容','rows'=>5,'required'=>true],
	]
];